-----------------------POLLS----------------------------
INSERT INTO Poll VALUES(1, 'Who is next Super Star?');
INSERT INTO Poll VALUES(2, 'Who is next Super Star?');
INSERT INTO Poll VALUES(3, 'Who is next Super Star?');
INSERT INTO Poll VALUES(4, 'Who is next Super Star?');
INSERT INTO Poll VALUES(5, 'Who is next Super Star?');
INSERT INTO Poll VALUES(6, 'Who is next Super Star?');
INSERT INTO Poll VALUES(7, 'Who is next Super Star?');
INSERT INTO Poll VALUES(8, 'Who is next Super Star?');
INSERT INTO Poll VALUES(9, 'Who is next Super Star?');
INSERT INTO Poll VALUES(10, 'Who is next Super Star?');
INSERT INTO Poll VALUES(11, 'Who is next Super Star?');
INSERT INTO Poll VALUES(12, 'Who is next Super Star?');
INSERT INTO Poll VALUES(13, 'Who is next Super Star?');
INSERT INTO Poll VALUES(14, 'Who is next Super Star?');
INSERT INTO Poll VALUES(15, 'Who is next Super Star?');
INSERT INTO Poll VALUES(16, 'Who is next Super Star?');
INSERT INTO Poll VALUES(17, 'Who is next Super Star?');
INSERT INTO Poll VALUES(18, 'Who is next Super Star?');
INSERT INTO Poll VALUES(19, 'Who is next Super Star?');
INSERT INTO Poll VALUES(20, 'Who is next Super Star?');
INSERT INTO Poll VALUES(21, 'Who is next Super Star?');
INSERT INTO Poll VALUES(22, 'Who is next Super Star?');
INSERT INTO Poll VALUES(23, 'Who is next Super Star?');
INSERT INTO Poll VALUES(24, 'Who is next Super Star?');
INSERT INTO Poll VALUES(25, 'Who is next Super Star?');
INSERT INTO Poll VALUES(26, 'Who is next Super Star?');
INSERT INTO Poll VALUES(27, 'Who is next Super Star?');
INSERT INTO Poll VALUES(28, 'Who is next Super Star?');
INSERT INTO Poll VALUES(29, 'Who is next Super Star?');
INSERT INTO Poll VALUES(30, 'Who is next Super Star?');
INSERT INTO Poll VALUES(31, 'Who is next Super Star?');
INSERT INTO Poll VALUES(32, 'Who is next Super Star?');
INSERT INTO Poll VALUES(33, 'Who is next Super Star?');
INSERT INTO Poll VALUES(34, 'Who is next Super Star?');
INSERT INTO Poll VALUES(35, 'Who is next Super Star?');
INSERT INTO Poll VALUES(36, 'Who is next Super Star?');
INSERT INTO Poll VALUES(37, 'Who is next Super Star?');
INSERT INTO Poll VALUES(38, 'Who is next Super Star?');
INSERT INTO Poll VALUES(39, 'Who is next Super Star?');
INSERT INTO Poll VALUES(40, 'Who is next Super Star?');
INSERT INTO Poll VALUES(41, 'Who is next Super Star?');
INSERT INTO Poll VALUES(42, 'Who is next Super Star?');
INSERT INTO Poll VALUES(43, 'Who is next Super Star?');
INSERT INTO Poll VALUES(44, 'Who is next Super Star?');
INSERT INTO Poll VALUES(45, 'Who is next Super Star?');
INSERT INTO Poll VALUES(46, 'Who is next Super Star?');
INSERT INTO Poll VALUES(47, 'Who is next Super Star?');
INSERT INTO Poll VALUES(48, 'Who is next Super Star?');
INSERT INTO Poll VALUES(49, 'Who is next Super Star?');
INSERT INTO Poll VALUES(50, 'Who is next Super Star?');
-----------------------POLL OPTIONS-------------------------------------
INSERT INTO Option VALUES(1, 'Ajith', 1);
INSERT INTO Option VALUES(2, 'Vijay', 1);
INSERT INTO Option VALUES(3, 'Ajith', 2);
INSERT INTO Option VALUES(4, 'Vijay', 2);
INSERT INTO Option VALUES(5, 'Ajith', 3);
INSERT INTO Option VALUES(6, 'Vijay', 3);
INSERT INTO Option VALUES(7, 'Ajith', 4);
INSERT INTO Option VALUES(8, 'Vijay', 4);
INSERT INTO Option VALUES(9, 'Ajith', 5);
INSERT INTO Option VALUES(10, 'Vijay', 5);
INSERT INTO Option VALUES(11, 'Ajith', 6);
INSERT INTO Option VALUES(12, 'Vijay', 6);
INSERT INTO Option VALUES(13, 'Ajith', 7);
INSERT INTO Option VALUES(14, 'Vijay', 7);
INSERT INTO Option VALUES(15, 'Ajith', 8);
INSERT INTO Option VALUES(16, 'Vijay', 8);
INSERT INTO Option VALUES(17, 'Ajith', 9);
INSERT INTO Option VALUES(18, 'Vijay', 9);
INSERT INTO Option VALUES(19, 'Ajith', 10);
INSERT INTO Option VALUES(20, 'Vijay', 10);
INSERT INTO Option VALUES(21, 'Ajith', 11);
INSERT INTO Option VALUES(22, 'Vijay', 11);
INSERT INTO Option VALUES(23, 'Ajith', 12);
INSERT INTO Option VALUES(24, 'Vijay', 12);
INSERT INTO Option VALUES(25, 'Ajith', 13);
INSERT INTO Option VALUES(26, 'Vijay', 13);
INSERT INTO Option VALUES(27, 'Ajith', 14);
INSERT INTO Option VALUES(28, 'Vijay', 14);
INSERT INTO Option VALUES(29, 'Ajith', 15);
INSERT INTO Option VALUES(30, 'Vijay', 15);
INSERT INTO Option VALUES(31, 'Ajith', 16);
INSERT INTO Option VALUES(32, 'Vijay', 16);
INSERT INTO Option VALUES(33, 'Ajith', 17);
INSERT INTO Option VALUES(34, 'Vijay', 17);
INSERT INTO Option VALUES(35, 'Ajith', 18);
INSERT INTO Option VALUES(36, 'Vijay', 18);
INSERT INTO Option VALUES(37, 'Ajith', 19);
INSERT INTO Option VALUES(38, 'Vijay', 19);
INSERT INTO Option VALUES(39, 'Ajith', 20);
INSERT INTO Option VALUES(40, 'Vijay', 20);
INSERT INTO Option VALUES(41, 'Ajith', 21);
INSERT INTO Option VALUES(42, 'Vijay', 21);
INSERT INTO Option VALUES(43, 'Ajith', 22);
INSERT INTO Option VALUES(44, 'Vijay', 22);
INSERT INTO Option VALUES(45, 'Ajith', 23);
INSERT INTO Option VALUES(46, 'Vijay', 23);
INSERT INTO Option VALUES(47, 'Ajith', 24);
INSERT INTO Option VALUES(48, 'Vijay', 24);
INSERT INTO Option VALUES(49, 'Ajith', 25);
INSERT INTO Option VALUES(50, 'Vijay', 25);
INSERT INTO Option VALUES(51, 'Ajith', 26);
INSERT INTO Option VALUES(52, 'Vijay', 26);
INSERT INTO Option VALUES(53, 'Ajith', 27);
INSERT INTO Option VALUES(54, 'Vijay', 27);
INSERT INTO Option VALUES(55, 'Ajith', 28);
INSERT INTO Option VALUES(56, 'Vijay', 28);
INSERT INTO Option VALUES(57, 'Ajith', 29);
INSERT INTO Option VALUES(58, 'Vijay', 29);
INSERT INTO Option VALUES(59, 'Ajith', 30);
INSERT INTO Option VALUES(60, 'Vijay', 30);
INSERT INTO Option VALUES(61, 'Ajith', 31);
INSERT INTO Option VALUES(62, 'Vijay', 31);
INSERT INTO Option VALUES(63, 'Ajith', 32);
INSERT INTO Option VALUES(64, 'Vijay', 32);
INSERT INTO Option VALUES(65, 'Ajith', 33);
INSERT INTO Option VALUES(66, 'Vijay', 33);
INSERT INTO Option VALUES(67, 'Ajith', 34);
INSERT INTO Option VALUES(68, 'Vijay', 34);
INSERT INTO Option VALUES(69, 'Ajith', 35);
INSERT INTO Option VALUES(70, 'Vijay', 35);
INSERT INTO Option VALUES(71, 'Ajith', 36);
INSERT INTO Option VALUES(72, 'Vijay', 36);
INSERT INTO Option VALUES(73, 'Ajith', 37);
INSERT INTO Option VALUES(74, 'Vijay', 37);
INSERT INTO Option VALUES(75, 'Ajith', 38);
INSERT INTO Option VALUES(76, 'Vijay', 38);
INSERT INTO Option VALUES(77, 'Ajith', 39);
INSERT INTO Option VALUES(78, 'Vijay', 39);
INSERT INTO Option VALUES(79, 'Ajith', 40);
INSERT INTO Option VALUES(80, 'Vijay', 40);
INSERT INTO Option VALUES(81, 'Ajith', 41);
INSERT INTO Option VALUES(82, 'Vijay', 41);
INSERT INTO Option VALUES(83, 'Ajith', 42);
INSERT INTO Option VALUES(84, 'Vijay', 42);
INSERT INTO Option VALUES(85, 'Ajith', 43);
INSERT INTO Option VALUES(86, 'Vijay', 43);
INSERT INTO Option VALUES(87, 'Ajith', 44);
INSERT INTO Option VALUES(88, 'Vijay', 44);
INSERT INTO Option VALUES(89, 'Ajith', 45);
INSERT INTO Option VALUES(90, 'Vijay', 45);
INSERT INTO Option VALUES(91, 'Ajith', 46);
INSERT INTO Option VALUES(92, 'Vijay', 46);
INSERT INTO Option VALUES(93, 'Ajith', 47);
INSERT INTO Option VALUES(94, 'Vijay', 47);
INSERT INTO Option VALUES(95, 'Ajith', 48);
INSERT INTO Option VALUES(96, 'Vijay', 48);
INSERT INTO Option VALUES(97, 'Ajith', 49);
INSERT INTO Option VALUES(98, 'Vijay', 49);
INSERT INTO Option VALUES(99, 'Ajith', 50);
INSERT INTO Option VALUES(100, 'Vijay', 50);
--------------------------------USERS-------------------------------------------
insert into users (user_id, username, password, first_name, last_name, admin) values(1, 'mickey', '$2a$10$kSqU.ek5pDRMMK21tHJlceS1xOc9Kna4F0DD2ZwQH/LAzH0ML0p6.', 'Mickey', 'Mouse', false);
insert into users (user_id, username, password, first_name, last_name, admin) values(2, 'minnie', '$2a$10$MnHcLn.XdLx.iMntXsmdgeO1B4wAW1E5GOy/VrLUmr4aAzabXnGFq', 'Minnie', 'Mouse', false);
insert into users (user_id, username, password, first_name, last_name, admin) values(3, 'donald', '$2a$10$0UCBI04PCXiK0pF/9kI7.uAXiHNQeeHdkv9NhA1/xgmRpfd4qxRMG', 'Donald', 'Duck', false);
insert into users (user_id, username, password, first_name, last_name, admin) values(4, 'daisy', '$2a$10$aNoR88g5b5TzSKb7mQ1nQOkyEwfHVQOxHY0HX7irI8qWINvLDWRyS', 'Daisy', 'Duck', false);
insert into users (user_id, username, password, first_name, last_name, admin) values(5, 'clarabelle', '$2a$10$cuTJd2ayEwXfsPdoF5/hde6gzsPx/gEiv8LZsjPN9VPoN5XVR8cKW', 'Clarabelle', 'Cow', false);
insert into users (user_id, username, password, first_name, last_name, admin) values(6, 'admin', '$2a$10$JQOfG5Tqnf97SbGcKsalz.XpDQbXi1APOf2SHPVW27bWNioi9nI8y', 'Super', 'Admin', true);





